SELECT bl."NOMBRE_BLOG" BLOG,
	   us."NOMBRE_USUARIO" USUARIO_CREADOR_BLOG,
	   po."DESCRIPCION_POSTEO" DESCRIPCION_POSTEO, us1."NOMBRE_USUARIO" USUARIO_POSTEO,
	   co."COMENTARIO" COMENTARIO, us2."NOMBRE_USUARIO" USUARIO_COMENTO
	
	
	FROM public."BLOG" bl,
		 public."COMENTARIO" co,
		 public."POSTEO" po,
		 public."USUARIO" us,
		 public."USUARIO" us1,
		 public."USUARIO" us2
		 

WHERE bl."USUARIO_ID_USUARIO" = us."ID_USUARIO"
  AND bl."ID_BLOG" = po."BLOG_ID_BLOG"
  AND po."ID_POSTEO" = co."POSTEO_ID_POSTEO"
  AND po."USUARIO_ID_USUARIO" = us1."ID_USUARIO"
  AND co."USUARIO_ID_USUARIO" = us2."ID_USUARIO"
  AND bl."USUARIO_ID_USUARIO" = us."ID_USUARIO"
  