-- Table: public.COMENTARIO

-- DROP TABLE IF EXISTS public."COMENTARIO";

CREATE TABLE IF NOT EXISTS public."COMENTARIO"
(
    "ID_COMENTARIO" integer NOT NULL,
    "POSTEO_ID_POSTEO" integer NOT NULL,
    "ESTADO_ID_ESTADO" integer NOT NULL,
    "COMENTARIO" character(100) COLLATE pg_catalog."default" NOT NULL,
    "FECHA_COMEN" date NOT NULL,
    "USUARIO_ID_USUARIO" integer,
    CONSTRAINT "COMENTARIO_pkey" PRIMARY KEY ("ID_COMENTARIO"),
    CONSTRAINT "FK_COMENTARIO_ESTADO" FOREIGN KEY ("ESTADO_ID_ESTADO")
        REFERENCES public."ESTADO" ("ID_ESTADO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "FK_COMENTARIO_POSTEO" FOREIGN KEY ("POSTEO_ID_POSTEO")
        REFERENCES public."POSTEO" ("ID_POSTEO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "FK_COMENTARIO_USUARIO" FOREIGN KEY ("USUARIO_ID_USUARIO")
        REFERENCES public."USUARIO" ("ID_USUARIO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."COMENTARIO"
    OWNER to postgres;