-- Table: public.POSTEO

-- DROP TABLE IF EXISTS public."POSTEO";

CREATE TABLE IF NOT EXISTS public."POSTEO"
(
    "ID_POSTEO" integer NOT NULL,
    "USUARIO_ID_USUARIO" integer NOT NULL,
    "BLOG_ID_BLOG" integer NOT NULL,
    "FECHA_POSTEO" date NOT NULL,
    "DESCRIPCION_POSTEO" character(100) COLLATE pg_catalog."default" NOT NULL,
    "ESTADO_ID_ESTADO" integer NOT NULL,
    CONSTRAINT "POSTEOS_pkey" PRIMARY KEY ("ID_POSTEO"),
    CONSTRAINT "FK_POSTEO_BLOG" FOREIGN KEY ("BLOG_ID_BLOG")
        REFERENCES public."BLOG" ("ID_BLOG") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "FK_POSTEO_ESTADO" FOREIGN KEY ("ESTADO_ID_ESTADO")
        REFERENCES public."ESTADO" ("ID_ESTADO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "FK_POSTEO_USUARIOS" FOREIGN KEY ("USUARIO_ID_USUARIO")
        REFERENCES public."USUARIO" ("ID_USUARIO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."POSTEO"
    OWNER to postgres;