-- Table: public.BLOG

-- DROP TABLE IF EXISTS public."BLOG";

CREATE TABLE IF NOT EXISTS public."BLOG"
(
    "ID_BLOG" integer NOT NULL,
    "NOMBRE_BLOG" character(20) COLLATE pg_catalog."default" NOT NULL,
    "DESCRIPCION_BLOG" character(100) COLLATE pg_catalog."default" NOT NULL,
    "FECHA_CREACION" date NOT NULL,
    "USUARIO_ID_USUARIO" integer NOT NULL,
    "ESTADO_ID_ESTADO" integer NOT NULL,
    CONSTRAINT "BLOG_pkey" PRIMARY KEY ("ID_BLOG"),
    CONSTRAINT "FK_BLOG_ESTADO" FOREIGN KEY ("ESTADO_ID_ESTADO")
        REFERENCES public."ESTADO" ("ID_ESTADO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "FK_BLOG_USUARIO" FOREIGN KEY ("USUARIO_ID_USUARIO")
        REFERENCES public."USUARIO" ("ID_USUARIO") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."BLOG"
    OWNER to postgres;